### PR TITLE
Contributions to Hometown 4.2 merge

### PR DESCRIPTION
**Pull request by dariusk**
This is a draft PR containing changes to the 4.2 merge work done by @nachtjasmin. It includes updates to a custom theme, Azure blob storage support, and a bugfix to render some preference menu hint text correctly. More custom theme work will be coming, and also I will add the work on the retractable menu here.

### CODE REVIEW

**Comment by nachtjasmin** [comment]
I think it's probably just the wrong upstream repo :D
Don't worry, I fucked this up often enough as well ^^

btw: feel free to push on my branch in #1337 as much as you want, I don't mind at all. or edit the PR if you want, it's completely up to you :3

**Comment by dariusk** [comment]
Oh this was entirely intentional. I'm trying to open a PR on your PR by proposing changes to your PR branch.

**Comment by dariusk** [comment]
(because I can't push code changes to your PR since I don't have write access to queer-group)

**Comment by nachtjasmin** [comment]
ugh, I thought I checked the checkmark to grant you access to the `lets-bump-hometown-to-mastodon-4.2` branch. sorry!

anyway, just tell me when it's done and then I'll merge it ^^

**Comment by nachtjasmin** [comment]
Closing this in favor of the upcoming release.

**Pull request closed without merging**
